23:05:45.17  Test starded without threads
21:05:45.564 Python Module Path 'ScriptKit' added.
21:05:45.564 Python Module Path 'Scripts/Gateway/SystemAreas/OrderProcessing/PythonModules' added.
21:05:45.564 Python Module Path 'ScriptKit/TroubleMaker' added.
21:05:45.564 Python Module Path 'Scripts/Gateway/PythonModules' added.
21:05:45.814 2020-02-19 Root suite 'Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/SynthSpread_VariableTickSize' full execution.
21:05:45.845 Suite '.'. [8 test cases, 0 sub-suites]
Traceback (most recent call last):
  File "C:\xpit.com\applications\ScriptFramework\ScriptKit\Core\Invoker.py", line 33, in invoke_script
    exec(code, globals())
  File "Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/SynthSpread_VariableTickSize\test_suite.su.py", line 77, in <module>
    generator.Open()
  File "C:\xpit.com\applications\ScriptFramework\ScriptKit\IHEGenerator.py", line 44, in Open
    self.__generator.Open(self.__name)
  File "C:\xpit.com\applications\ScriptFramework\ScriptKit\ModuleAgent.py", line 8898, in Open
    return _ModuleAgent.IIHEGenerator_Open(self, name)
RuntimeError: Failed to resolve interface  (from Interface): interface not found.
Available interfaces:
name=\DEVICE\TCPIP_{CFF7A875-51FB-48C1-9B78-ABA35ACC4BDF}, ip=172.26.65.55, network=172.26.65.0, up=1
name=\DEVICE\TCPIP_{1F777394-0B42-11E3-80AD-806E6F6E6963}, ip=127.0.0.1, network=127.0.0.0, up=1


21:05:54.048 Suite '.' setup failed, child test cases and sub-suites will be skipped.
21:05:54.142 Root suite 'Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/SynthSpread_VariableTickSize' execution finished. It took 0:00:08.312728.
21:05:54.142 Test cases results: 8 total, 0 succeeded, 0 failed, 8 skipped.
